theme: minima
title: Max Hedeman Joosten
description: Bookmark this to keep an eye on my project updates!
<script type="text/javascript" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
